name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
    - run: npm install -g vsce
    - run: vsce package --out ios-debug.vsix
    - uses: actions/upload-artifact@v2
      with:
        path: ios-debug.vsix
